Repository infinum/eightshift-boilerplate, pull requests merged in 2019-03, with the labels that each got.

#131 Added optional script arguments to install script
  bin/theme-setup.js
  package-lock.json
  package.json
  packages/create-wp-theme/README.md
  packages/create-wp-theme/package.json
  packages/create-wp-theme/theme-setup.js
Labels: development

#129 Missing manifest entires while watching fix
  webpack.config.js
Labels: bug

#132 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, future release

#126 Add ellipsis only if the source string is longer than the limit
  theme/utils/class-excerpt.php
Labels: enhancement, future release
